M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu22.04.1} date 2025-02-12T21:26:31+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-12T21:26:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X57.0Y-110.0
X58.6Y-74.0
X106.0Y-54.0
X106.5Y-110.0
M30
